get: 
  tags: 
    -  Product
  summary: "Get a list of products."
  description: "Returns a list of products."
  operationId: listProducts
  responses: 
    '200': 
      description: "Successful operation."
      content: 
        application/json: 
          schema: 
            $ref: '../../components/schemas/v1/product_list.yaml'
    '404': 
      description: "Not found."
      content: 
        application/json: 
          schema: 
            $ref: '../../components/schemas/Problem.yaml'
post:
  tags:
    - Product
  summary: "Create a new product."
  description: "Creates a new product."
  operationId: createProduct
  requestBody: 
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/v1/product_create.yaml'
    
  responses:
    '201':
      description: "Product created."
      headers:
        Location:
          description: "The location of the created product."
          schema:
            type: string
            format: uri
            example: "/v1/products/123e4567-e89b-12d3-a456-426614174000"
    '400':
      description: "Bad request."
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/Problem.yaml'
  