get: 
  tags: 
    -  Product
  summary: "Get a list of products."
  operationId: listProducts
  responses: 
    '200': 
      description: "Successful operation."
      content: 
        application/json: 
          schema: 
            $ref: '../../components/schemas/v1/product_list.yaml'
    '401': 
      description: "Unauthorized."
    '403': 
      description: "Forbidden."
    '404': 
      description: "Not found."
      content: 
        application/json: 
          schema: 
            $ref: '../../components/schemas/Problem.yaml'
    '500': 
      description: "Internal server error."